set fish_color_autosuggestion 'brblack'
set fish_color_cancel '-r'
set fish_color_command '--bold'
set fish_color_comment 'brblack'
set fish_color_cwd 'brcyan'
set fish_color_cwd_root 'brred'
set fish_color_end 'brmagenta'
set fish_color_error 'brred'
set fish_color_escape 'brblack' '--bold'
set fish_color_host 'brblack'
set fish_color_match '--background=brblue'
set fish_color_normal 'normal'
set fish_color_operator 'bryellow'
set fish_color_param 'brcyan'
set fish_color_quote 'bryellow'
set fish_color_redirection 'brblue'
set fish_color_search_match 'bryellow' '--background=brblack'
set fish_color_selection 'brwhite' '--bold' '--background=brblack'
set fish_color_user 'brgreen'
set fish_color_valid_path '--underline'
