#!/usr/bin/env bash

export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export GOPATH="$XDG_DATA_HOME/go"
export GOCACHE="$XDG_CACHE_HOME/go"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker-machine"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"
export PYLINTHOME="$XDG_CACHE_HOME/pylint"
export PIP_CONFIG_FILE="$XDG_CONFIG_HOME/pip/pip.conf"
export PARALLEL_HOME="$XDG_CONFIG_HOME/parallel"
# export CARGO_HOME="$XDG_DATA_HOME/cargo"
# export PIPENV_VENV_IN_PROJECT=1
# export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
# export NPM_CONFIG_PREFIX="$XDG_DATA_HOME/npm"
# export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
# export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
# export GEM_HOME="$XDG_DATA_HOME/gem"
# export GEM_SPEC_CACHE="$XDG_CACHE_HOME/gem"
# export GEMRC="$XDG_CONFIG_HOME/gem/gemrc"
# export RBENV_ROOT="$XDG_DATA_HOME/rbenv"
# export STACK_ROOT="$XDG_DATA_HOME/stack"
# export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
# export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
# export _JAVA_OPTIONS="Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
